export const words = [
  'toothbrush',
  'backpack',
  'alarm clock',
  'remote control',
  'keyboard',
  'mouse',
  'headphones',
  'charger',
  'water bottle',
  'coffee mug',
  'traffic light',
  'ceiling fan',
  'refrigerator',
  'washing machine',
  'microwave',
  'television',
  'sofa',
  'dining table',
  'curtain',
  'window',
  'doorbell',
  'staircase',
  'elevator',
  'dustbin',
  'shopping cart',
  'umbrella',
  'helmet',
  'bus stop',
  'streetlight',
  'notebook',
  'pen stand',
  'calculator',
  'wallet',
  'credit card',
  'shoe rack',
  'bed',
  'pillow',
  'blanket',
  'mirror',
  'comb',
  'shampoo bottle',
  'towel',
  'soap',
  'plate',
  'spoon',
  'frying pan',
  'gas stove',
  'laptop',
  'mobile phone',
  'watch',
];
